version: "3"
services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    ports:
      - "33000:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - :/var/lib/mysql
      - :/etc/mysql